# Generated by Django 4.1.7 on 2023-07-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='foo', max_length=100)),
                ('axis_X', models.IntegerField(default=0)),
                ('axis_Y', models.IntegerField(default=0)),
                ('rotation', models.IntegerField(default=0)),
                ('font_size', models.IntegerField(default=0)),
                ('font_type', models.CharField(default='foo', max_length=100)),
            ],
        ),
    ]
