# Generated by Django 4.1.7 on 2023-07-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_type',
            field=models.CharField(default='foo', max_length=100),
        ),
    ]
