# Generated by Django 4.1.7 on 2023-08-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasave', '0002_data_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='batch',
            field=models.IntegerField(default=0),
        ),
    ]
